apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i6vqpv1ps-python 
  janus-idp.io/tekton: i6vqpv1ps-python
  backstage.io/kubernetes-id: i6vqpv1ps-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i6vqpv1ps-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml